In [95]:
import numpy as np

In [97]:
#MATRIX 1D
mat1d = np.array([1,2,3,4,5,6,7,8,9,10])
mat2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [99]:
print(mat1d)
print(mat1d[0])

[ 1  2  3  4  5  6  7  8  9 10]
1


In [101]:
print(mat1d + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [103]:
print(mat2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
print(mat2d[0])
print(mat2d[1])
print(mat2d[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [107]:
print(mat2d[0][2])

3


In [109]:
print(mat2d * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [111]:
print(mat1d.shape)
print(mat2d.shape)

(10,)
(3, 3)


In [113]:
print(mat1d.size)
print(mat2d.size)

10
9


In [115]:
#special matrix
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [117]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [119]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [121]:
print(mFull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [123]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [91]:
print(mRandomFloat)

[[0.95882392 0.61155563 0.28605111 0.34810014 0.32206257]
 [0.12005652 0.46511863 0.84651704 0.82399179 0.00710049]
 [0.92145989 0.68813523 0.14310535 0.12781282 0.07516127]
 [0.17631186 0.6450412  0.82581172 0.86212052 0.69331035]
 [0.64760183 0.19829368 0.10063719 0.06072357 0.45166684]]


In [93]:
print(mRandomInt)

[85 12 57 96 59 25]


In [129]:
x = np.array([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)


print(f" hasil dari dot product : {dotProduct}")
print(f" hasil penjualan matrix : {addMatrix}")
print(f" hasil nilai minimum : {minValue}")
print(f" hasil nilai maksimum : {maxValue}")
print(f" rata rata nilai dari : {meanValue}")
print(f" nilai tengah dari : {medianValue}")
print(f" nilai deviasi dari  : {stdValue}")

 hasil dari dot product : 65
 hasil penjualan matrix : [ 3  9 14]
 hasil nilai minimum : 2
 hasil nilai maksimum : 5
 rata rata nilai dari : 3.0
 nilai tengah dari : 3.0
 nilai deviasi dari  : 1.632993161855452


In [138]:
myArray = np.array([[1,2,3],[4,5,6]])

reshape = myArray.reshape(3,2)
flatten = myArray.flatten()

print(reshape)
print(flatten)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [142]:
#filtering
nilaiSiswa = np.array([80,90,60,50,50,100,95])
lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = lulus.size
print(lulus)
print(f"Jumlah siswa yang lulus : {jumlah}")

[ 80  90  60 100  95]
Jumlah siswa yang lulus : 5
